// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: heroacademy-proto.proto

package heroacademy_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroName string `protobuf:"bytes,1,opt,name=hero_name,json=heroName,proto3" json:"hero_name,omitempty"`
	Quirk    string `protobuf:"bytes,2,opt,name=quirk,proto3" json:"quirk,omitempty"`
}

func (x *HeroRequest) Reset() {
	*x = HeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heroacademy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroRequest) ProtoMessage() {}

func (x *HeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_heroacademy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroRequest.ProtoReflect.Descriptor instead.
func (*HeroRequest) Descriptor() ([]byte, []int) {
	return file_heroacademy_proto_rawDescGZIP(), []int{0}
}

func (x *HeroRequest) GetHeroName() string {
	if x != nil {
		return x.HeroName
	}
	return ""
}

func (x *HeroRequest) GetQuirk() string {
	if x != nil {
		return x.Quirk
	}
	return ""
}

type HeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *HeroResponse) Reset() {
	*x = HeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heroacademy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroResponse) ProtoMessage() {}

func (x *HeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_heroacademy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroResponse.ProtoReflect.Descriptor instead.
func (*HeroResponse) Descriptor() ([]byte, []int) {
	return file_heroacademy_proto_rawDescGZIP(), []int{1}
}

func (x *HeroResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_heroacademy_proto protoreflect.FileDescriptor

var file_heroacademy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x65, 0x72, 0x6f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x65, 0x72, 0x6f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79,
	0x22, 0x40, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x72, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x69, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x69,
	0x72, 0x6b, 0x22, 0x26, 0x0a, 0x0c, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x55, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x72,
	0x6f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x61, 0x63, 0x61, 0x64, 0x65,
	0x6d, 0x79, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x19, 0x5a, 0x17, 0x6b, 0x61, 0x6c, 0x6c, 0x70, 0x61, 0x2d, 0x63, 0x6f, 0x64, 0x65,
	0x2f, 0x68, 0x65, 0x72, 0x6f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_heroacademy_proto_rawDescOnce sync.Once
	file_heroacademy_proto_rawDescData = file_heroacademy_proto_rawDesc
)

func file_heroacademy_proto_rawDescGZIP() []byte {
	file_heroacademy_proto_rawDescOnce.Do(func() {
		file_heroacademy_proto_rawDescData = protoimpl.X.CompressGZIP(file_heroacademy_proto_rawDescData)
	})
	return file_heroacademy_proto_rawDescData
}

var file_heroacademy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heroacademy_proto_goTypes = []any{
	(*HeroRequest)(nil),  // 0: heroacademy-proto.HeroRequest
	(*HeroResponse)(nil), // 1: heroacademy-proto.HeroResponse
}
var file_heroacademy_proto_depIdxs = []int32{
	0, // 0: heroacademy-proto.TrainingService.TrainHero:input_type -> heroacademy-proto.HeroRequest
	1, // 1: heroacademy-proto.TrainingService.TrainHero:output_type -> heroacademy-proto.HeroResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_heroacademy_proto_init() }
func file_heroacademy_proto_init() {
	if File_heroacademy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heroacademy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_heroacademy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heroacademy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_heroacademy_proto_goTypes,
		DependencyIndexes: file_heroacademy_proto_depIdxs,
		MessageInfos:      file_heroacademy_proto_msgTypes,
	}.Build()
	File_heroacademy_proto = out.File
	file_heroacademy_proto_rawDesc = nil
	file_heroacademy_proto_goTypes = nil
	file_heroacademy_proto_depIdxs = nil
}
